version: '3.9'

services:
  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - "./create-database.sql:/docker-entrypoint-initdb.d/create-database.sql"
