version: '3.9'

services:
  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - api
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - "./create-database.sql:/docker-entrypoint-initdb.d/create-database.sql"
